Recommendation-Systems/DataScience/Models/UserItem/Article.cs
using System.Collections.Generic;

namespace DataScience.Models.UserItem
{
    public class Article
    {
        public int Id;

        public Article(int id)
        {
            Id = id;
        }

        /// <summary>
        /// Create user models from the provided list with array of strings.
        /// </summary>
        public static SortedDictionary<int, Article> Populate(IEnumerable<string[]> ratings)
        {
            var models = new SortedDictionary<int, Article>();
            foreach (var rating in ratings)
            {
                var articleId = int.Parse(rating[1]);

                if (models.ContainsKey(articleId))
                {
                    continue;
                }

                models.Add(articleId, new Article(articleId));
            }
            
            return models;
        }
    }
}

Recommendation-Systems/DataScience/Models/UserItem/User.cs
using System.Collections.Generic;
using System.Text;

namespace DataScience.Models.UserItem
{
    public class User
    {
        public readonly int Id;
        public readonly Dictionary<int, float> Ratings;

        public User(int id)
        {
            Id = id;
            Ratings = new Dictionary<int, float>();
        }

        public void AddRating(int articleId, float rating)
        {
            Ratings.Add(articleId, rating);
        }

        /// <summary>
        /// Create user models from the provided list with array of strings.
        /// </summary>
        public static SortedDictionary<int, User> Populate(IEnumerable<string[]> ratings)
        {
            var models = new SortedDictionary<int, User>();
            foreach (var rating in ratings)
            {
                var userId = int.Parse(rating[0]);
                var articleId = int.Parse(rating[1]);
                var grade = float.Parse(rating[2]);

                if (!models.TryGetValue(userId, out var model))
                {
                    model = new User(userId);
                    models.Add(userId, model);
                }
                
                model.AddRating(articleId, grade);
            }

            return models;
        }
    }
}

Recommendation-Systems/DataScience/Controllers/HomeController.cs
using System.Web.Mvc;

namespace DataScience.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

Recommendation-Systems/DataScience/Controllers/UserItemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DataScience.Models.UserItem;
using DataScience.Services;
using DataScience.Services.Similarity;

namespace DataScience.Controllers
{
    public class UserItemController : Controller
    {
        // GET
        public ActionResult Index()
        {
            ViewBag.Message = "Ratings";
            ViewBag.Users = GetUsers(GetPayload());
            ViewBag.Articles = GetArticles(GetPayload());

            return View();
        }

        // GET
        public ActionResult View(string userId)
        {
            var castedUserId = int.Parse(userId);
            var payload = GetPayload();
            var users = GetUsers(payload);
            var articles = GetArticles(payload);

            // Throw not found exception if user is not listed
            if (!users.ContainsKey(castedUserId))
            {
                throw new HttpException(404, "Not found");
            }

            var user = users[castedUserId];
            
            ViewBag.UserId = castedUserId;
            ViewBag.Users = users;
            ViewBag.User = user;
            ViewBag.Articles = articles;
            
            const float threshold = 0.35f;
            var neighborHelper = new NearestNeighbors(users.Values.ToList(), user, articles);
            ViewBag.Neighbors = new Dictionary<string, IEnumerable<Tuple<User, float>>>
            {
                {"pearson", neighborHelper.ListSimilarities(new Pearson(), threshold)},
                {"cosine", neighborHelper.ListSimilarities(new Cosine(), threshold)},
                {"euclidean", neighborHelper.ListSimilarities(new Euclidean(), threshold)}
            };

            return View();
        }

        /// <summary>
        /// Get payload used in this controller.
        /// </summary>
        private static List<string[]> GetPayload()
        {
            return DataSetLoader.Load("userItem");
        }

        /// <summary>
        /// Get users from the provided payload.
        /// </summary>
        private static SortedDictionary<int, User> GetUsers(IEnumerable<string[]> payload)
        {
            return Models.UserItem.User.Populate(payload);
        }

        /// <summary>
        /// Get articles from the provided payload.
        /// </summary>
        private static SortedDictionary<int, Article> GetArticles(IEnumerable<string[]> payload)
        {
            return Article.Populate(payload);
        }
    }
}

Recommendation-Systems/DataScience/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home";
}
<h2>@ViewBag.Title</h2>

<p>Data Science learning project site.</p>

Recommendation-Systems/DataScience/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - Data Science</title>
    <link rel="stylesheet" href="~/Content/bootstrap.css"/>
    <link rel="stylesheet" href="~/Content/site.css"/>
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        @Html.ActionLink("Data Science", "Index", "Home", null, new {@class = "navbar-brand"})
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    @Html.ActionLink("Home", "Index", "Home", null, new {@class = "nav-link"})
                </li>
                <li class="nav-item">
                    @Html.ActionLink("User-Item", "Index", "UserItem", null, new {@class = "nav-link"})
                </li>
            </ul>
        </div>
    </div>
</nav>

<div class="container body-content">
    @RenderBody()
    <hr/>
    <footer>
        <p>&copy; 2018 - Maarten de Graaf (0908765)</p>
    </footer>
</div>

<environment names="Development">
    <script src="~/Scripts/jquery-3.3.1.js"></script>
    <script src="~/Scripts/bootstrap.js"></script>
    <script src="~/Scripts/site.js"></script>
</environment>

@RenderSection("scripts", false)
</body>
</html>

Recommendation-Systems/DataScience/Views/UserItem/Index.cshtml
@{
    ViewBag.Title = "User-Item";
}
<h2>@ViewBag.Title</h2>
<h3>@ViewBag.Message</h3>

<table class="table table-bordered table-hover">
    <thead>
    <tr>
        <th></th>
        @foreach (var article in ViewBag.Articles)
        {
            <th>@article.Key</th>
        }
        <th></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var user in ViewBag.Users)
    {
        <tr>
            <th>@user.Value.Id</th>
            @foreach (var article in ViewBag.Articles)
            {
                <td>
                    @if (user.Value.Ratings.ContainsKey(article.Key))
                    {
                        @user.Value.Ratings[article.Key]
                    }
                    else
                    {
                        @("-")
                    }
                </td>
            }
            <td class="td-compact">
                @Html.ActionLink("View similarities", "View", "UserItem", new {userId = user.Value.Id}, new {@class = "btn btn-light"})
            </td>
        </tr>
    }
    </tbody>
</table>

Recommendation-Systems/DataScience/Views/UserItem/View.cshtml
@using DataScience.Services.Similarity
@using DataScience.Models.UserItem
@{ ViewBag.Title = "User ID: " + ViewBag.UserId; }
@{ User user = ViewBag.User; }
<h2>@ViewBag.Title</h2>

<table class="table table-bordered table-hover">
    <thead>
    <tr>
        <th></th>
        @foreach (var article in ViewBag.Articles)
        {
            <th>@article.Key</th>
        }
        <th>Similarity</th>
    </tr>
    </thead>
    <tbody>
    @foreach (KeyValuePair<int, User> userItem in ViewBag.Users)
    {
        <tr class="@(userItem.Key == user.Id ? "table-active" : "")">
            <th>@userItem.Value.Id</th>
            @foreach (var article in ViewBag.Articles)
            {
                <td>
                    @if (userItem.Value.Ratings.ContainsKey(article.Key))
                    {
                        @userItem.Value.Ratings[article.Key]
                    }
                    else
                    {
                        @("-")
                    }
                </td>
            }
            <td class="td-compact">
                @{ var similarity = new SimilarityWrapper(new SimilarityList(userItem.Value.Ratings, user.Ratings, ViewBag.Articles)); }
                Euclidean: @Math.Round(similarity.Euclidean(), 4)<br/>
                Manhatttan: @Math.Round(similarity.Manhattan(), 4)<br/>
                Pearson: @Math.Round(similarity.Pearson(), 4)<br/>
                Cosine: @Math.Round(similarity.Cosine(), 4)
            </td>
        </tr>
    }
    </tbody>
</table>

@foreach (KeyValuePair<string, IEnumerable<Tuple<User, float>>> neighbor in ViewBag.Neighbors)
{
    <h3>Nearest Neighbors: @neighbor.Key</h3>
    <table class="table table-bordered table-hover">
        <thead>
        <tr>
            <th></th>
            @foreach (var article in ViewBag.Articles)
            {
                <th>@article.Key</th>
            }
            <th>Similarity</th>
        </tr>
        </thead>
        <tbody>
        @foreach (var userItem in neighbor.Value)
        {
            <tr>
                <th>@userItem.Item1.Id</th>
                @foreach (var article in ViewBag.Articles)
                {
                    <td>
                        @if (userItem.Item1.Ratings.ContainsKey(article.Key))
                        {
                            @userItem.Item1.Ratings[article.Key]
                        }
                        else
                        {
                            @("-")
                        }
                    </td>
                }
                <td class="td-compact">
                    @userItem.Item2
                </td>
            </tr>
        }
        </tbody>
    </table>
}